<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>14</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyTitle>BloomEngine</AssemblyTitle>
		<Description>Robust mod menu and config manager for PvZ Replanted.</Description>
		<Version>0.3.0-beta</Version>
		<Authors>PalmForest</Authors>
		<Company>PalmForest</Company>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup>
		<GamePath>C:\Program Files (x86)\Steam\steamapps\common\PVZ Replanted</GamePath>
	</PropertyGroup>
	
	<ItemGroup>
		<EmbeddedResource Include="Resources\**\*" />
		<None Remove="Resources\**\*" />
	</ItemGroup>

	<!-- MelonLoader, Harmony, Il2CppInterop -->
	<ItemGroup>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)\MelonLoader\net6\MelonLoader.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)\MelonLoader\net6\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>$(GamePath)\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>$(GamePath)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<!-- All other assemblies -->
	<ItemGroup>
		<Reference Include="$(GamePath)\MelonLoader\Il2CppAssemblies\*.dll">
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
